[general]
name = "sandbox-container-pattree"
version = "0.1.0"

[build]
files = [
    "treap.fix",
]
opt_level = "basic"
# dynamic_links = ["dmalloc"]

[build.test]
files = [
]
opt_level = "max"

[[dependencies]]
name = "minilib-common"
version = "*"
git = { url = "https://github.com/pt9999/fixlang-minilib-common.git" }


[[dependencies]]
name = "random"
version = "*"
git = { url = "https://github.com/tttmmmyyyy/fixlang-random.git" }
