[general]
name = "sandbox-ioref"
version = "0.1.0"
fix_version = "1.2.0"
authors = ["pt9999"]
license = "MIT"

[build]
opt_level = "basic"
files = [
    "ioref.fix",
]

objects = ["lib.o"]
preliminary_commands = [["make", "lib.o", "CFLAGS=-g"]]

[build.test]
files = [
    "test.fix",
]


[[dependencies]]
name = "minilib-common"
version = "0.7.3"
git = { url = "https://github.com/pt9999/fixlang-minilib-common.git" }