[general]
name = "sandbox-text-sprintf"
version = "0.1.0"
fix_version = "1.2.0"
authors = ["pt9999"]
license = "MIT"

[build]
opt_level = "basic"
files = [
    "lib/text/sprintf.fix",
    "lib/text/sprintf/sprintf_internal.fix",
]

[build.test]
opt_level = "basic"
files = [
    "tests/test.fix",
    "tests/text/sprintf_test.fix",
    "tests/text/sprintf/sprintf_internal_test.fix",
]

[[dependencies]]
name = "minilib-common"
version = "*"
git = { url = "https://github.com/pt9999/fixlang-minilib-common.git" }

[[dependencies]]
name = "minilib-text"
version = "*"
git = { url = "https://github.com/pt9999/fixlang-minilib-text.git" }

[[dependencies]]
name = "minilib-binary"
version = "*"
git = { url = "https://github.com/pt9999/fixlang-minilib-binary.git" }