[general]
name = "sandbox-ffi"
version = "0.0.1"
authors = ["pt9999"]
license = "MIT"

[build]
opt_level = "basic"
files = [
    "lib/ffi/retained_ptr.fix",
    "lib/ffi/typename.fix",
    "lib/ffi/typed_ptr.fix",
]

[build.test]
opt_level = "max"
files = [
    "tests/test.fix",
    "tests/ffi/retained_ptr_test.fix",
]

[[dependencies]]
name = "asynctask"
version = "1.1.2"
git = { url = "https://github.com/tttmmmyyyy/fixlang-asynctask.git" }

[[dependencies]]
name = "minilib-common"
version = "0.7.3"
git = { url = "https://github.com/pt9999/fixlang-minilib-common.git" }