[general]
name = "sandbox-text-wchar"
version = "0.1.0"
fix_version = "1.2.0"

[build]
files = [
    "locale.fix",
    "wide_char.fix",
]
objects = ["lib.o"]
preliminary_commands = [["make", "lib.o"]]

[build.test]
files = [
    "tests/wide_char_test.fix",
    "tests/locale_test.fix",
    "tests/test.fix",
]

[[dependencies]]
name = "minilib-text"
version = "0.6.1"
git = { url = "https://github.com/pt9999/fixlang-minilib-text.git" }