[general]
name = "sandbox-terminal-filer"
version = "0.1.0"

[build]
output = "filer.out"
files = [
    "filer.fix",
    "src/common.fix",
    "src/disk_usage.fix",
    "src/list_view.fix",
    "src/file_item.fix",
    "src/file_list_view.fix",
    "src/file_view.fix",
    "src/status_view.fix",
]
opt_level = "basic"

[build.test]
files = [
    "tests/test.fix",
    "tests/disk_usage_test.fix",
]

[[dependencies]]
name = "minilib-io"
version = "*"
git = { url = "https://github.com/pt9999/fixlang-minilib-io.git" }

[[dependencies]]
name = "minilib-monad"
version = "*"
git = { url = "https://github.com/pt9999/fixlang-minilib-monad.git" }

[[dependencies]]
name = "minilib-text"
version = "*"
git = { url = "https://github.com/pt9999/fixlang-minilib-text.git" }

[[dependencies]]
name = "minilib-thread"
version = "*"
git = { url = "https://github.com/pt9999/fixlang-minilib-thread.git" }

[[dependencies]]
name = "sandbox-ncurses"
version = "*"
# git = { url = "https://github.com/pt9999/fixlang-minilib-ncurses.git" }
path = "../ncurses"

[[dependencies]]
name = "hashmap"
version = "*"
git = { url = "https://github.com/tttmmmyyyy/fixlang-hashmap.git" }
