[general]
name = "publisher"
version = "0.1.0"
fix_version = "1.2.0"
authors = ["pt9999"]
license = "MIT"

[build]
files = [
    "main.fix",
    "process_runner.fix"
]
opt_level = "basic"


[[dependencies]]
name = "minilib-common"
version = "*"
git = { url = "https://github.com/pt9999/fixlang-minilib-common.git" }

[[dependencies]]
name = "minilib-io"
version = "*"
git = { url = "https://github.com/pt9999/fixlang-minilib-io.git" }

[[dependencies]]
name = "minilib-monad"
version = "*"
git = { url = "https://github.com/pt9999/fixlang-minilib-monad.git" }

[[dependencies]]
name = "minilib-collection"
version = "*"
git = { url = "https://github.com/pt9999/fixlang-minilib-collection.git" }


[[dependencies]]
name = "minilib-app"
version = "0.5.5"
git = { url = "https://github.com/pt9999/fixlang-minilib-app.git" }

[[dependencies]]
name = "subprocess"
version = "1.0.7"
git = { url = "https://github.com/tttmmmyyyy/fixlang-subprocess.git" }