[general]
name = "publisher"
version = "0.1.0"
fix_version = "1.2.0"
authors = ["pt9999"]
license = "MIT"

[build]
output = "publisher.out"
files = [
    "main.fix",
    "src/common.fix",
    "src/console_ui.fix",
    "src/main.fix",
    "src/publish.fix",
    "src/process_runner.fix",
    "src/project_file.fix",
    "src/verup.fix",
]
opt_level = "basic"

[build.test]
files = [
    "tests/test.fix",
    "tests/publish_test.fix",
    "tests/mock_process_runner.fix",
]
opt_level = "basic"

[[dependencies]]
name = "minilib-common"
version = "*"
git = { url = "https://github.com/pt9999/fixlang-minilib-common.git" }

[[dependencies]]
name = "minilib-io"
version = "*"
git = { url = "https://github.com/pt9999/fixlang-minilib-io.git" }

[[dependencies]]
name = "minilib-monad"
version = "*"
git = { url = "https://github.com/pt9999/fixlang-minilib-monad.git" }

[[dependencies]]
name = "minilib-collection"
version = "*"
git = { url = "https://github.com/pt9999/fixlang-minilib-collection.git" }


[[dependencies]]
name = "minilib-app"
version = "*"
git = { url = "https://github.com/pt9999/fixlang-minilib-app.git" }

[[dependencies]]
name = "subprocess"
version = "*"
git = { url = "https://github.com/tttmmmyyyy/fixlang-subprocess.git" }

[[dependencies]]
name = "regexp"
version = "*"
git = { url = "https://github.com/tttmmmyyyy/fixlang-regexp.git" }