[general]
name = "publisher"
version = "0.1.0"
fix_version = "1.2.0"
authors = ["pt9999"]
license = "MIT"

[build]
files = [
    "main.fix",
    "src/app.fix",
    "src/app_env.fix",
    "src/common.fix",
    "src/console_ui.fix",
    "src/env.fix",
    "src/fs.fix",
    "src/logger.fix",
    "src/process_runner.fix",
    "src/project_file.fix",
    "src/project_version.fix",
    "src/publish.fix",
]
opt_level = "basic"

[build.test]
files = [
    "tests/test.fix",
    "tests/app_test.fix",
    "tests/publish_test.fix",
    "tests/console_ui_test.fix",
    "tests/project_file_test.fix",
    "tests/mock_env.fix",
    "tests/mock_process_runner.fix",
    "tests/mock_console_ui.fix",
    "tests/mock_fs.fix",
]
opt_level = "basic"

[[dependencies]]
name = "asynctask"
version = "*"
git = { url = "https://github.com/tttmmmyyyy/fixlang-asynctask.git" }

[[dependencies]]
name = "hashmap"
version = "*"
git = { url = "https://github.com/tttmmmyyyy/fixlang-hashmap.git" }

[[dependencies]]
name = "subprocess"
version = "*"
git = { url = "https://github.com/tttmmmyyyy/fixlang-subprocess.git" }

[[dependencies]]
name = "regexp"
version = "*"
git = { url = "https://github.com/tttmmmyyyy/fixlang-regexp.git" }

[[dependencies]]
name = "minilib-common"
version = "*"
git = { url = "https://github.com/pt9999/fixlang-minilib-common.git" }

[[dependencies]]
name = "minilib-io"
version = "*"
git = { url = "https://github.com/pt9999/fixlang-minilib-io.git" }

[[dependencies]]
name = "minilib-monad"
version = "*"
git = { url = "https://github.com/pt9999/fixlang-minilib-monad.git" }

[[dependencies]]
name = "minilib-app"
version = "*"
git = { url = "https://github.com/pt9999/fixlang-minilib-app.git" }

