[general]
name = "sandbox-container-rbtree2"
version = "0.1.0"

[build]
files = [
    "rbtree2.fix", 
]
opt_level = "basic"

[build.test]
files = [
    "rbtree2_test.fix",
]
opt_level = "basic"

[[dependencies]]
name = "minilib-common"
version = "*"
git = { url = "https://github.com/pt9999/fixlang-minilib-common.git" }
