[general]
name = "sandbox-container-rbtree2"
version = "0.1.0"

[build]
files = [
#    "rbtree1.fix", 
#    "rbtree2.fix", 
]
opt_level = "basic"

[build.test]
files = [
#    "rbtree1_test.fix",
#    "rbtree2_test.fix",
    "test_util_array.fix",
    "test.fix",
]
opt_level = "basic"

[[dependencies]]
name = "minilib-common"
version = "*"
git = { url = "https://github.com/pt9999/fixlang-minilib-common.git" }


[[dependencies]]
name = "random"
version = "1.1.1"
git = { url = "https://github.com/tttmmmyyyy/fixlang-random.git" }