[general]
name = "sandbox-container-rbtree2"
version = "0.1.0"

[build]
files = [
#    "rbtree3.fix", 
    "rbtree4.fix", 
#    "tree_set3.fix",
]
opt_level = "basic"

[build.test]
files = [
    "rbtree_test.fix",
#    "rbtree3_test.fix",
    "rbtree4_test.fix",
    "test_util_array.fix",
    "test.fix",
]
opt_level = "basic"
# dynamic_links = ["dmalloc"]

[[dependencies]]
name = "minilib-common"
version = "*"
git = { url = "https://github.com/pt9999/fixlang-minilib-common.git" }


[[dependencies]]
name = "random"
version = "1.1.1"
git = { url = "https://github.com/tttmmmyyyy/fixlang-random.git" }

[[dependencies]]
name = "minilib-collection"
version = "0.6.0"
git = { url = "https://github.com/pt9999/fixlang-minilib-collection.git" }