[general]
name = "sandbox-toml"
version = "0.1.0"

[build]
files = [
    "lib/encoding/toml.fix",
    "lib/encoding/toml/toml_reader.fix",
]
opt_level = "basic"

[[dependencies]]
name = "minilib-common"
version = "*"
git = { url = "https://github.com/pt9999/fixlang-minilib-common.git" }

[[dependencies]]
name = "minilib-text"
version = "*"
git = { url = "https://github.com/pt9999/fixlang-minilib-text.git" }
