[general]
name = "sandbox-thread-asynctest"
version = "0.1.0"
fix_version = "1.2.0"

[build]
files = ["async_test.fix"]
threaded = true

[build.test]
files = []

[[dependencies]]
name = "asynctask"
#version = "=1.1.1"     # for fix version 2025/12/20
#version = "=1.1.2"       # for fix version 2025/12/24
version = "1.1.3"
git = { url = "https://github.com/tttmmmyyyy/fixlang-asynctask.git" }