[general]
name = "sandbox-container-pattree"
version = "0.1.0"

[build]
files = [
    "pattree.fix",
    "pattree2.fix",
    "pattree3.fix",
    "intmap.fix",
    "pattree_test.fix",
    "pattree2_test.fix",
    "pattree3_test.fix",
    "intmap_test.fix",
    "test_util_array.fix",
    "test.fix",
]
opt_level = "max"
# dynamic_links = ["dmalloc"]

[build.test]
files = [
]
opt_level = "max"

[[dependencies]]
name = "minilib-common"
version = "*"
git = { url = "https://github.com/pt9999/fixlang-minilib-common.git" }


[[dependencies]]
name = "random"
version = "1.1.1"
git = { url = "https://github.com/tttmmmyyyy/fixlang-random.git" }

[[dependencies]]
name = "minilib-binary"
version = "0.5.1"
git = { url = "https://github.com/pt9999/fixlang-minilib-binary.git" }