[general]
name = "sandbox-container-rbtree1"
version = "0.1.0"

[build]
files = [
    "rbtree.fix", 
]
opt_level = "basic"

[build.test]
files = [
    "rbtree_test.fix",
    "test_util_array.fix",
    "test.fix",
]
opt_level = "max"

[[dependencies]]
name = "minilib-common"
version = "*"
git = { url = "https://github.com/pt9999/fixlang-minilib-common.git" }


[[dependencies]]
name = "random"
version = "1.1.1"
git = { url = "https://github.com/tttmmmyyyy/fixlang-random.git" }